### ISSUE TITLE
Out of memory with KroneckerEK0 using 50K dimensions

### ISSUE THREAD

**Issue by Plinkett** [pnkraemer/tornadox#141]
Hi!

I tried running the KroneckerEK0 with the Lorenz96 ODE and 50000 dimensions. Using the Kronecker factorization I should be able to get linear complexity in the dimensions. I am using adaptive step-size with 4 derivatives. I tried running the following code:

```python
import jax.numpy as jnp
from tornadox import ek0, ivp

solver = ek0.KroneckerEK0(num_derivatives=4)

# Solve an IVP
lorenz96 = ivp.lorenz96(tmax=0.6, num_variables=50000)


# Full solve
print(solver)
solver.solve(lorenz96)
    
print()
```

But I get the following error:

```
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
KroneckerEK0(num_derivatives=4, steprule=AdaptiveSteps(abstol=0.0001, reltol=0.01), initialization=TaylorMode())
Traceback (most recent call last):
  File "/home/santillan/pykf/probdiffeq_test.py", line 19, in <module>
    solver.solve(vdp)
  File "/home/santillan/pykf/venv/lib/python3.10/site-packages/tornadox/odefilter.py", line 62, in solve
    cov_sqrtms.append(state.y.dense_cov_sqrtm())
  File "/home/santillan/pykf/venv/lib/python3.10/site-packages/tornadox/rv.py", line 73, in dense_cov_sqrtm
    return jnp.kron(self.cov_sqrtm_1, self.cov_sqrtm_2)
  File "/graphics/opt/opt_Ubuntu22.04/python/3.10/opt-packages/local/lib/python3.10/dist-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/graphics/opt/opt_Ubuntu22.04/python/3.10/opt-packages/local/lib/python3.10/dist-packages/jax/_src/pjit.py", line 250, in cache_miss
    outs, out_flat, out_tree, args_flat, jaxpr = _python_pjit_helper(
  File "/graphics/opt/opt_Ubuntu22.04/python/3.10/opt-packages/local/lib/python3.10/dist-packages/jax/_src/pjit.py", line 163, in _python_pjit_helper
    out_flat = pjit_p.bind(*args_flat, **params)
  File "/graphics/opt/opt_Ubuntu22.04/python/3.10/opt-packages/local/lib/python3.10/dist-packages/jax/_src/core.py", line 2677, in bind
    return self.bind_with_trace(top_trace, args, params)
  File "/graphics/opt/opt_Ubuntu22.04/python/3.10/opt-packages/local/lib/python3.10/dist-packages/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/graphics/opt/opt_Ubuntu22.04/python/3.10/opt-packages/local/lib/python3.10/dist-packages/jax/_src/core.py", line 815, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/graphics/opt/opt_Ubuntu22.04/python/3.10/opt-packages/local/lib/python3.10/dist-packages/jax/_src/pjit.py", line 1203, in _pjit_call_impl
    return xc._xla.pjit(name, f, call_impl_cache_miss, [], [], donated_argnums,
  File "/graphics/opt/opt_Ubuntu22.04/python/3.10/opt-packages/local/lib/python3.10/dist-packages/jax/_src/pjit.py", line 1187, in call_impl_cache_miss
    out_flat, compiled = _pjit_call_impl_python(
  File "/graphics/opt/opt_Ubuntu22.04/python/3.10/opt-packages/local/lib/python3.10/dist-packages/jax/_src/pjit.py", line 1143, in _pjit_call_impl_python
    return compiled.unsafe_call(*args), compiled
  File "/graphics/opt/opt_Ubuntu22.04/python/3.10/opt-packages/local/lib/python3.10/dist-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/graphics/opt/opt_Ubuntu22.04/python/3.10/opt-packages/local/lib/python3.10/dist-packages/jax/_src/interpreters/pxla.py", line 1349, in __call__
    results = self.xla_executable.execute_sharded(input_bufs)
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory allocating 500000000000 bytes.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/santillan/pykf/probdiffeq_test.py", line 19, in <module>
    solver.solve(vdp)
  File "/home/santillan/pykf/venv/lib/python3.10/site-packages/tornadox/odefilter.py", line 62, in solve
    cov_sqrtms.append(state.y.dense_cov_sqrtm())
  File "/home/santillan/pykf/venv/lib/python3.10/site-packages/tornadox/rv.py", line 73, in dense_cov_sqrtm
    return jnp.kron(self.cov_sqrtm_1, self.cov_sqrtm_2)
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory allocating 500000000000 bytes.
```

It tries to allocate 500GB of data. Am I implicitly computing the full covariance matrix at some point?

**Comment by pnkraemer** [comment]
Hi,

Thanks for reaching out! 

I am a bit confused because your error message does not seem to match the code snippet: it complains about `solver.solve(vdp)`, but your example should run `solver.solve(lorenz)`. Maybe you mixed something up there, and maybe this mix-up is the reason for your error?


P.S.:
Also, as indicated in Tornadox's readme, we don't really work on tornadox anymore. Other libraries can do what Tornadox does (and more). There is https://github.com/pnkraemer/probdiffeq for JAX code or https://github.com/nathanaelbosch/ProbNumDiffEq.jl for Julia code, and you might enjoy working with these libraries more than working with Tornadox :blush:  What do you think?

**Comment by pnkraemer** [comment]
In addition to the above:

You might be looking for solver.solution_generator() or solver.simulate_final_state() because solver.solve() is more of a convenience function to plot solutions etc. solver.solve() indeed materialises the full covariance matrices.
Have a look at tornadox/odefilter.py to see how these functions compare, and let me know if you need further assistance.

Does this help? :)

**Comment by Plinkett** [comment]
Ops, you are correct. The error message indeed referred to another code snippet.  Problem's the same though. However just using 
```python  
simulate_final_state(lorenz96) 
```
works! So I was previously materializing the full covariance matrix.

Thanks! I've also checked out probdiffeq and it works like a charm :)

P.S. The only reason I am looking at Tornadox is that I am trying to implement the probabilistic solver in PyTorch and Tornadox seemed easier to translate w.r.t. probdiffeq (I am using the Probabilistic ODE Solutions in Millions of Dimensions paper as reference). Again, thank you so much!

**Comment by pnkraemer** [comment]
That's great to hear! Thanks for following up :) 

> P.S. The only reason I am looking at Tornadox is that I am trying to implement the probabilistic solver in PyTorch and Tornadox seemed easier to translate w.r.t. probdiffeq (I am using the Probabilistic ODE Solutions in Millions of Dimensions paper as reference). Again, thank you so much!

Oh, that sounds super interesting, and I agree that Tornadox could be a better reference for this process -- at least at this point in time. If you use the million-dimensions paper as a reference, you might also be interested in [this](https://scholar.google.com/citations?view_op=view_citation&hl=de&user=BGufKRsAAAAJ&citation_for_view=BGufKRsAAAAJ:eQOLeE2rZwMC).  

Let me know if you have more questions :+1:
